module.exports = {
    ACCOUNT_STATUS_ACTIVE : '1',
    ACCOUNT_STATUS_DEACTIVE : '2',
    DEPARTMENT_STATUS_ACTIVE : '1',
    DEPARTMENT_STATUS_DEACTIVE : '2',
    EMPLOYEE_ROLE: '2',
    ADMIN_ROLE: '1',
    EMPLOYEE_STATUS_ACTIVE : '1',
    EMPLOYEE_STATUS_DEACTIVE : '2',
}